### ISSUE TITLE
Task #3

### ISSUE THREAD

**Issue by irenkart** [KokhanevychD/Python_internship#13]
1) `Multiple_vars` -  **не** называй функции и переменные с большой буквы или в CamelCase, используй snake_case
2) По поводу функции `Multiple_vars`, можно было сделать, примерно так `multiple_vars(_out_list=[], some_int, global_int=globe_scope_var)` т.е. без объявления исходящего списка в глобальных переменных
3) В функции `KwargsSample` можно было просто сделать `print(args, kwargs)`. Но твое решение - не является ошибкой. Так же не рекомендуется переименовывать *args, **kwargs в другие названия, т.к. это стандартное их название и у других людей могут возникнуть проблемы с чтением кода.
4) `is_divisible_by` можно упростить до 1 строки, подумай как.

**Comment by KokhanevychD** [comment]
> 1. `Multiple_vars` -  **не** называй функции и переменные с большой буквы или в CamelCase, используй snake_case
> 2. По поводу функции `Multiple_vars`, можно было сделать, примерно так `multiple_vars(_out_list=[], some_int, global_int=globe_scope_var)` т.е. без объявления исходящего списка в глобальных переменных
> 3. В функции `KwargsSample` можно было просто сделать `print(args, kwargs)`. Но твое решение - не является ошибкой. Так же не рекомендуется переименовывать *args, **kwargs в другие названия, т.к. это стандартное их название и у других людей могут возникнуть проблемы с чтением кода.
> 4. `is_divisible_by` можно упростить до 1 строки, подумай как.

Внес исправления
