### ISSUE TITLE
Task #7

### ISSUE THREAD

**Issue by irenkart** [KokhanevychD/Python_internship#15]
1) В requirements проскочила строчка pkg-resources==0.0.0 из-за чего pip install не срабатывает.
2) settings файл лучше импортировать так django.conf import settings, а не from internship import settings
3) следующие импорты можно делать 1 строкой, через ","
 ```
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
```
4) Ну и про гит игнор не забывай, например у меня, когда я развернул твой проект, сразу куча unversioned файлов появилась из .idea
<img width="469" alt="image" src="https://user-images.githubusercontent.com/37925411/79547420-89994c00-809c-11ea-8fca-f7513fe9155e.png">

**Comment by KokhanevychD** [comment]
странно, .idea у меня там вообще не было
pkg-resources==0.0.0 это баг пип на убунту, поищу как исправить
остальное пофиксил
